Repository DeviousLabs/git-secrets-replacer, pull requests merged in 2024-10, with the labels that each got.

#12 Workflow Updates.
  .github/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/scanning.yml
Labels: documentation, enhancement

#13 ReadMe Updates
  README.md
  Security.md
Labels: documentation

#15 Update README.md
  README.md
Labels: documentation, enhancement

#16 SLSA Report generation and cosign keyless signing
  .github/workflows/release.yml
Labels: documentation, enhancement

#17 Updated Cosign Workflow action
  .github/workflows/release.yml
Labels: bug, enhancement

#18 workflow update
  .github/workflows/release.yml
Labels: bug, enhancement

#19 Workflow Changes
  .github/workflows/release.yml
Labels: bug, enhancement

#21 syntax fix.
  .github/workflows/release.yml
Labels: bug

#23 Removed SLSA generation for now, this can be addressed later.
  .github/workflows/release.yml
Labels: bug

#22 Added test.yml and Updated release.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  internal/replacer/processing_test.go
  main.go
Labels: enhancement

#24 Updated release.yml and test.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement

#25 added codeowners file
  .github/CODEOWNERS
Labels: enhancement

#27 Fix: Ensure secrets are consistently removed, improve blob and tree processing
  internal/replacer/processing.go
  internal/replacer/processing_test.go
Labels: bug, enhancement

#28 Update README.md
  README.md
Labels: documentation

#29 Progress Bar Feature & Org Fixes
  go.mod
  go.sum
  internal/replacer/processing.go
  main.go
Labels: documentation, enhancement

#30 Feature fuzzing
  .github/workflows/fuzztest.yml
  internal/replacer/processing_test.go
  internal/replacer/utils_test.go
Labels: enhancement

#32 Update README.md
  README.md
Labels: documentation

#33 Features: Improved workflows
  .github/workflows/codeql.yml
  .github/workflows/openssf.yml
  .github/workflows/release.yml
Labels: enhancement

#34 Fix: updated token permissions
  .github/workflows/release.yml
Labels: enhancement
